# config\packages\nelmio_api_doc.yaml

nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: >
                **The best API for mobile phones**.<br />  To get your token, unfold the **POST** ~~/api/login_check~~ section, click on
                _'Try it out'_ then 'Execute.<br />  In the Response body, copy the string from _'token'_.<br /> Back to the top of the
                page, click on _'Authorize'_ and in the input field type **'bearer'** + **space** + **'THE_STRING_YOU'VE_COPIED'**.<br />
                You can now use the API :)
            version: 1.0.0
        paths:
            /api/login_check:
                post:
                    operationId: postCredentialsItem
                    tags:
                        - Token
                    summary: Great you a token in order to get logged.
                    requestBody:
                        description: Create a new JWT token
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Catch the JWT token
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: admin@example.com
                        password:
                            type: string
                            default: password
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
